name: "nestjs-boilerplate"
services:
    service:
        image: nestjs-boilerplate-sevice:latest
        container_name: service-dev
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        env_file:
            - .env
        command: npm run start:debug
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - 3000:3000
            - 9233:9233
        depends_on:
            - redis-dev
        networks:
            - nesjs-network
        restart: unless-stopped

    # Redis service
    redis-dev:
        image: redis:alpine
        container_name: nestjs-redis-dev
        ports:
            - 6379:6379
        env_file:
            - .env
        volumes:
            - redis:/data
        networks:
            - nesjs-network

volumes:
    redis:
        driver: local

networks:
    nesjs-network:
        driver: bridge
